name: push-dockerhub
on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: add env tag
        run: echo ${{ github.ref }}
        env:
          REF: ${{ github.ref }}
        run: echo "${REF##*/}"
          TAG: "${REF##*/v}"
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yoshiken/yoshiken.dev.python:${TAG}
